# Use Ubuntu as base image
FROM ubuntu:24.04

# Avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install Python, pip, and Mosquitto
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-add-repository ppa:mosquitto-dev/mosquitto-ppa && \
    apt-get update && \
    apt-get install -y mosquitto mosquitto-clients && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install Python dependencies
COPY requirements.txt .

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir --timeout 120 -r requirements.txt


# Copy FastAPI code
COPY . .

# Expose ports # 8000 for api service, 9001 & 8883 for mqtt broker
EXPOSE 8000 9001 8883

# Run the script
CMD ["./start.sh"]
