"""Add validation_code col to streaming_clients table

Revision ID: 116e81290752
Revises: 778e67b92e34
Create Date: 2025-10-02 13:57:38.015090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '116e81290752'
down_revision: Union[str, Sequence[str], None] = '778e67b92e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    columns = [col['name'] for col in inspector.get_columns('streaming_clients')]
    if 'validation_code' not in columns:
        op.add_column('streaming_clients', sa.Column('validation_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    columns = [col['name'] for col in inspector.get_columns('streaming_clients')]
    if 'validation_code' in columns:
        op.drop_column('streaming_clients', 'validation_code')
    # ### end Alembic commands ###
