"""Update Controller Model

Revision ID: 2987a6598871
Revises: 
Create Date: 2025-12-28 04:06:19.488526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2987a6598871'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('controllers_name_key'), 'controllers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('controllers_name_key'), 'controllers', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
