"""add validation_code to users

Revision ID: 4b212724d225
Revises: 
Create Date: 2025-10-26 07:18:51.922748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '4b212724d225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'validation_code' not in [c['name'] for c in inspector.get_columns('users')]:
        op.add_column('users', sa.Column('validation_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'validation_code' in [c['name'] for c in inspector.get_columns('users')]:
        op.drop_column('users', 'validation_code')
    # ### end Alembic commands ###