"""Update MqttTopicModel

Revision ID: 4c380d5ec802
Revises: 78c1461d4356
Create Date: 2025-11-10 07:05:26.085371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c380d5ec802'
down_revision: Union[str, Sequence[str], None] = '78c1461d4356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mqtt_topics', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mqtt_topics', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
