"""create chat model

Revision ID: 4e6ef59f0c09
Revises: 77bf761aee3e
Create Date: 2025-11-22 06:38:56.508256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6ef59f0c09'
down_revision: Union[str, Sequence[str], None] = '77bf761aee3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_conversations', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('mqtt_topics', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mqtt_topics', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'chat_conversations', type_='foreignkey')
    op.drop_column('chat_conversations', 'session_id')
    # ### end Alembic commands ###
