"""changed ondelete action on uavs table

Revision ID: 86a96f807c1f
Revises: 4e6ef59f0c09
Create Date: 2025-12-06 07:18:35.159179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a96f807c1f'
down_revision: Union[str, Sequence[str], None] = '4e6ef59f0c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uavs_station_id_fkey'), 'uavs', type_='foreignkey')
    op.create_foreign_key(None, 'uavs', 'stations', ['station_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uavs', type_='foreignkey')
    op.create_foreign_key(op.f('uavs_station_id_fkey'), 'uavs', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
