"""Update MqttTopicModel

Revision ID: 9678bfdc2038
Revises: c42fbd406bac
Create Date: 2025-11-10 07:02:43.837115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9678bfdc2038'
down_revision: Union[str, Sequence[str], None] = 'c42fbd406bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_topics', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mqtt_topics', 'is_default')
    # ### end Alembic commands ###
