"""Update ControllerModel

Revision ID: b3c54b25f2e8
Revises: fa8938c32b11
Create Date: 2025-10-16 02:32:07.950547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c54b25f2e8'
down_revision: Union[str, Sequence[str], None] = 'fa8938c32b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'controllers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'controllers', type_='foreignkey')
    op.drop_column('controllers', 'user_id')
    # ### end Alembic commands ###
