"""Alter name col in streaming_urls as unique

Revision ID: d8a9b6a24644
Revises: 116e81290752
Create Date: 2025-10-06 08:50:32.616188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a9b6a24644'
down_revision: Union[str, Sequence[str], None] = '116e81290752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_urls_name'), table_name='streaming_urls')
    op.create_index(op.f('ix_streaming_urls_name'), 'streaming_urls', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_urls_name'), table_name='streaming_urls')
    op.create_index(op.f('ix_streaming_urls_name'), 'streaming_urls', ['name'], unique=False)
    # ### end Alembic commands ###
