FROM python:3.9-slim-bookworm

# Install dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libgl1 \
    libusb-1.0-0-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt . 
COPY depth_cam_obj_dect_streaming.py . 
COPY yolo11n.onnx .

# Install python packages
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the script
CMD ["python", "-u", "depth_cam_obj_dect_streaming.py"]