[[inputs.mqtt_consumer]]
  servers = ["tcp://backend_facsec:8883"]
  topics = ["#"]
  data_format = "value"
  data_type="string"
  username = "admin"  
  password = "adminpass"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb_facsec:8086"]
  token = "RlVt24FSrictAEKFz0UHh1iB8D0MRYw8z0mLw0sOHzCZElcKuzpz2GR5-3w25vHbUkGsntcFjN6D0V5WfuY-Nw=="
  organization = "drtech"
  bucket = "drsys"
