[[inputs.mqtt_consumer]]
  servers = ["tcp://backend_facsec:8883"]
  topics = ["#"]
  data_format = "value"
  data_type="string"
  username = "admin"  
  password = "adminpass"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb_facsec:8086"]
  token = "SlDLJJs16nBEZ5WfhkDb0sCu0Ap_AQTiJ4eLdgI-dIkn81wI0cC8oA6g-dOMFjC3CshTSzaJhxUys03FxPzHWg=="
  organization = "drtech"
  bucket = "drsys"
